apiVersion: v1
kind: Service
metadata:
  name: kubernetesdemoapp-service
  namespace: default
  labels:
    app: kubernetesdemoapp
spec:
  selector:
    app: kubernetesdemoapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer